# Generated by Django 4.0.4 on 2022-06-23 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_order_address_order_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.BooleanField(default=False),
        ),
    ]
